#!/bin/bash

# Message function
msg () {
	echo "************ $1 ************"
}

# Installation prefix
prefix=/usr

# Directory where source files are downloaded and built
src_dir="$HOME/src/compiz-reloaded-0.8.14"

num_cores="$(grep -c '^processor' /proc/cpuinfo)"

build_component () {
	c="$1"
	cd "$src_dir/$c-0.8.14"
	# ccsm uses python configuration/installation script
	if [ "$c" = "ccsm" ]; then
		sudo ./setup.py build --prefix="$prefix" || return 1

		return 0
	fi
	msg "Configuring $c"
	if [ "$c" = "core" ]; then
		./autogen.sh --prefix="$prefix" --disable-gnome --disable-kde --disable-kde4 || return 1
        else
		./autogen.sh --prefix="$prefix" || return 1
	fi
	msg "Compiling $c"
	make -j"$num_cores" || return 1

	return 0
}

if test "$1"; then
	build_component "$1" || { msg "$1 compilation failed" && exit 1; }
	exit 0
fi

while read component; do
	build_component "$component" || { msg "$c compilation failed" && exit 1; }
done < ./components.list

exit 0
