#!/bin/bash

# Message function
msg () {
	echo "************ $1 ************"
}

# Installation prefix
prefix=/usr

# Directory where source files are downloaded and built
src_dir="$HOME/src/compiz-reloaded-0.8.14"

# Number of cpu cores available
num_cores="$(grep -c '^processor' /proc/cpuinfo)"

install_component () {
	c="$1"
	cd "$src_dir/$c-0.8.14"
	msg "Installing $c"
	if [ "$c" = "ccsm" ]; then
		if [ -f /etc/debian_version ]; then
			sudo ./setup.py install --prefix="$prefix" --install-layout=deb || return 1
		else
			sudo ./setup.py install --prefix="$prefix" || return 1
		fi

		return 0
	fi
	sudo make -j"$num_cores" install || return 1

	return 0
}

if test "$1"; then
	install_component "$1" || { msg "$1 installation failed" && exit 1; }
	exit 0
fi

while read component; do
	cd "$src_dir"
	install_component "$component" || { msg "$component failed to install"; exit 1; }
done < ./components.list

exit 0
