#!/bin/bash

# Message function
msg () {
	echo "************ $1 ************"
}

# Installation prefix
prefix=/usr

# Directory where source files were downloaded and built
src_dir="$HOME/src/compiz-reloaded-0.8.14"

# Number of cpu cores available
num_cores="$(grep -c '^processor' /proc/cpuinfo)"

uninstall_component () {
	c="$1"
	cd "$src_dir/$c-0.8.14"
	msg "Uninstalling $c"
	if [ "$c" = "ccsm" ]; then
		sudo ./setup.py uninstall --prefix="$prefix" || return 1
		return 0
	fi
	sudo make -j"$num_cores" uninstall || return 1

	return 0
}

if test "$1"; then
	uninstall_component "$1" || { msg "$1 removal failed" && exit 1; }
	exit 0
fi

while read component; do
	cd "$src_dir"
	uninstall_component "$component" || { msg "$component failed to uninstall"; exit 1; }
done < ./components.list

exit 0
